"""`mcpify output-server` — bake a serve command into a shareable script.

The generated file is a small, readable Python script that replays a
`mcpify serve ...` command with all flags pre-applied: teammates run
`python3 server.py` and get the identical MCP server without remembering
the flags. What it is, honestly:

- the script REQUIRES mcpify-openapi installed in its environment (the
  header says so, with the minimum version); it calls the public CLI
  entry point, so behavior can never drift from the installed mcpify
- a LOCAL spec is embedded into the script (base64 of the raw file, so
  quoting can never break); a REMOTE spec stays a URL fetched at start
- credentials are never embedded: only env-variable NAMES travel in the
  script; --http-token is the one flag that would embed a secret, so it
  triggers a loud warning at generation time
"""

from __future__ import annotations

import base64
import json
from pathlib import Path

from . import __version__

MIN_MCPIFY = "1.6"

TEMPLATE = '''#!/usr/bin/env python3
r"""Standalone MCP server generated by `mcpify output-server`.

Requires mcpify-openapi >= {min_version} installed where this runs:

    pip install mcpify-openapi

Run it:

    python3 {name}

This replays the preconfigured command:

    mcpify serve {display_ref}{baked}

Generated by mcpify {version}.
"""

import os
import sys
import tempfile

# Raw bytes of the OpenAPI document (base64), embedded at generation time.
# None when the spec is a remote URL: SPEC_URL is fetched at startup then.
SPEC_B64 = {spec_b64}
SPEC_URL = {spec_url}

BAKED = {baked_arg}


def main() -> None:
    from mcpify.cli import main as cli_main

    path = SPEC_URL
    tmp_name = None
    if SPEC_B64 is not None:
        import base64 as _base64

        fd, tmp_name = tempfile.mkstemp(prefix="mcpify-", suffix=".json")
        with os.fdopen(fd, "wb") as handle:
            handle.write(_base64.b64decode(SPEC_B64))
        path = tmp_name
    try:
        cli_main(["serve", path] + BAKED)
    finally:
        if tmp_name is not None:
            try:
                os.unlink(tmp_name)
            except OSError:
                pass


if __name__ == "__main__":
    main()
'''


def build_script(
    display_ref: str,
    spec_b64: str | None,
    spec_url: str | None,
    baked: list[str],
    outfile_name: str,
) -> str:
    baked_text = ("".join(" " + part for part in baked)) if baked else ""
    return TEMPLATE.format(
        min_version=MIN_MCPIFY,
        version=__version__,
        name=Path(outfile_name).name,
        display_ref=display_ref,
        baked=baked_text,
        spec_b64=json.dumps(spec_b64) if spec_b64 is not None else "None",
        spec_url=json.dumps(spec_url) if spec_url is not None else "None",
        baked_arg=json.dumps(baked),
    )


def generate(
    spec_path: str,
    output_path: str,
    baked_flags: list[str],
    force: bool = False,
) -> list[str]:
    """Write the standalone script. Returns warnings (printed by the CLI).

    Raises ValueError with a user-facing message on refusal."""
    from .spec import SpecError, load_spec

    target = Path(output_path)
    if target.exists() and not force:
        raise ValueError(f"{output_path} already exists — pass --force to overwrite")
    spec_b64: str | None = None
    spec_url: str | None = None
    if spec_path.startswith(("http://", "https://")):
        spec_url = spec_path
    else:
        raw = Path(spec_path).read_bytes()
        try:
            load_spec(spec_path)  # fail fast: never ship a script that can't parse
        except SpecError as err:
            raise ValueError(f"spec is not usable: {err}") from None
        spec_b64 = base64.b64encode(raw).decode("ascii")

    # the generated docstring is a raw string: backslashes stay readable,
    # but a triple quote inside it would terminate it — refuse instead of
    # shipping a script with a SyntaxError
    triple = chr(34) * 3
    if triple in Path(spec_path).name or any(triple in flag for flag in baked_flags):
        raise ValueError(
            "path or flags contain triple quotes, which cannot be embedded "
            "in the generated script's docstring"
        )

    warnings: list[str] = []
    if "--http-token" in baked_flags:
        warnings.append(
            "--http-token is baked into the script as PLAIN TEXT — anyone with "
            "the file has the token. Prefer MCPIFY_HTTP_TOKEN in the environment."
        )

    script = build_script(spec_path, spec_b64, spec_url, baked_flags, target.name)
    target.write_text(script, encoding="utf-8")
    return warnings
